# This file has been generated by node2nix 1.1.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "chokidar-1.6.0" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-1.6.0.tgz";
        sha1 = "90c32ad4802901d7713de532dc284e96a63ad058";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "optionator-0.8.2" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.2.tgz";
        sha1 = "364c5e409d3f4d6301d6c0b4c05bba50180aeb64";
      };
    };
    "riot-compiler-2.5.5" = {
      name = "riot-compiler";
      packageName = "riot-compiler";
      version = "2.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/riot-compiler/-/riot-compiler-2.5.5.tgz";
        sha1 = "04e5849bcd595ed491657b6891083c76eb6ea580";
      };
    };
    "rollup-0.36.3" = {
      name = "rollup";
      packageName = "rollup";
      version = "0.36.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup/-/rollup-0.36.3.tgz";
        sha1 = "c89ac479828924ff8f69c1d44541cb4ea2fc11fc";
      };
    };
    "shelljs-0.7.4" = {
      name = "shelljs";
      packageName = "shelljs";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/shelljs/-/shelljs-0.7.4.tgz";
        sha1 = "b8f04b3a74ddfafea22acf98e0be45ded53d59c8";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.0.0.tgz";
        sha1 = "c5061b6e0ef8a81775e50f5d66151bf6bf371107";
      };
    };
    "anymatch-1.3.0" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-1.3.0.tgz";
        sha1 = "a3e52fa39168c825ff57b0248126ce5a8ff95507";
      };
    };
    "async-each-1.0.1" = {
      name = "async-each";
      packageName = "async-each";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-each/-/async-each-1.0.1.tgz";
        sha1 = "19d386a1d9edc6e7c1c85d388aedbcc56d33602d";
      };
    };
    "glob-parent-2.0.0" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-2.0.0.tgz";
        sha1 = "81383d72db054fcccf5336daa902f182f6edbb28";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "is-binary-path-1.0.1" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-1.0.1.tgz";
        sha1 = "75f16642b480f187a711c814161fd3a4a7655898";
      };
    };
    "is-glob-2.0.1" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-2.0.1.tgz";
        sha1 = "d096f926a3ded5600f3fdfd91198cb0888c2d863";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "readdirp-2.1.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-2.1.0.tgz";
        sha1 = "4ed0ad060df3073300c48440373f72d1cc642d78";
      };
    };
    "fsevents-1.0.14" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "1.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-1.0.14.tgz";
        sha1 = "558e8cc38643d8ef40fe45158486d0d25758eee4";
      };
    };
    "arrify-1.0.1" = {
      name = "arrify";
      packageName = "arrify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/arrify/-/arrify-1.0.1.tgz";
        sha1 = "898508da2226f380df904728456849c1501a4b0d";
      };
    };
    "micromatch-2.3.11" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "2.3.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-2.3.11.tgz";
        sha1 = "86677c97d1720b363431d04d0d15293bd38c1565";
      };
    };
    "arr-diff-2.0.0" = {
      name = "arr-diff";
      packageName = "arr-diff";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-diff/-/arr-diff-2.0.0.tgz";
        sha1 = "8f3b827f955a8bd669697e4a4256ac3ceae356cf";
      };
    };
    "array-unique-0.2.1" = {
      name = "array-unique";
      packageName = "array-unique";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-unique/-/array-unique-0.2.1.tgz";
        sha1 = "a1d97ccafcbc2625cc70fadceb36a50c58b01a53";
      };
    };
    "braces-1.8.5" = {
      name = "braces";
      packageName = "braces";
      version = "1.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-1.8.5.tgz";
        sha1 = "ba77962e12dff969d6b76711e914b737857bf6a7";
      };
    };
    "expand-brackets-0.1.5" = {
      name = "expand-brackets";
      packageName = "expand-brackets";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-brackets/-/expand-brackets-0.1.5.tgz";
        sha1 = "df07284e342a807cd733ac5af72411e581d1177b";
      };
    };
    "extglob-0.3.2" = {
      name = "extglob";
      packageName = "extglob";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extglob/-/extglob-0.3.2.tgz";
        sha1 = "2e18ff3d2f49ab2765cec9023f011daa8d8349a1";
      };
    };
    "filename-regex-2.0.0" = {
      name = "filename-regex";
      packageName = "filename-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/filename-regex/-/filename-regex-2.0.0.tgz";
        sha1 = "996e3e80479b98b9897f15a8a58b3d084e926775";
      };
    };
    "is-extglob-1.0.0" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-1.0.0.tgz";
        sha1 = "ac468177c4943405a092fc8f29760c6ffc6206c0";
      };
    };
    "kind-of-3.0.4" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-3.0.4.tgz";
        sha1 = "7b8ecf18a4e17f8269d73b501c9f232c96887a74";
      };
    };
    "normalize-path-2.0.1" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-2.0.1.tgz";
        sha1 = "47886ac1662760d4261b7d979d241709d3ce3f7a";
      };
    };
    "object.omit-2.0.0" = {
      name = "object.omit";
      packageName = "object.omit";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.omit/-/object.omit-2.0.0.tgz";
        sha1 = "868597333d54e60662940bb458605dd6ae12fe94";
      };
    };
    "parse-glob-3.0.4" = {
      name = "parse-glob";
      packageName = "parse-glob";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-glob/-/parse-glob-3.0.4.tgz";
        sha1 = "b2c376cfb11f35513badd173ef0bb6e3a388391c";
      };
    };
    "regex-cache-0.4.3" = {
      name = "regex-cache";
      packageName = "regex-cache";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/regex-cache/-/regex-cache-0.4.3.tgz";
        sha1 = "9b1a6c35d4d0dfcef5711ae651e8e9d3d7114145";
      };
    };
    "arr-flatten-1.0.1" = {
      name = "arr-flatten";
      packageName = "arr-flatten";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-flatten/-/arr-flatten-1.0.1.tgz";
        sha1 = "e5ffe54d45e19f32f216e91eb99c8ce892bb604b";
      };
    };
    "expand-range-1.8.2" = {
      name = "expand-range";
      packageName = "expand-range";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-range/-/expand-range-1.8.2.tgz";
        sha1 = "a299effd335fe2721ebae8e257ec79644fc85337";
      };
    };
    "preserve-0.2.0" = {
      name = "preserve";
      packageName = "preserve";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/preserve/-/preserve-0.2.0.tgz";
        sha1 = "815ed1f6ebc65926f865b310c0713bcb3315ce4b";
      };
    };
    "repeat-element-1.1.2" = {
      name = "repeat-element";
      packageName = "repeat-element";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-element/-/repeat-element-1.1.2.tgz";
        sha1 = "ef089a178d1483baae4d93eb98b4f9e4e11d990a";
      };
    };
    "fill-range-2.2.3" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-2.2.3.tgz";
        sha1 = "50b77dfd7e469bc7492470963699fe7a8485a723";
      };
    };
    "is-number-2.1.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-2.1.0.tgz";
        sha1 = "01fcbbb393463a548f2f466cce16dece49db908f";
      };
    };
    "isobject-2.1.0" = {
      name = "isobject";
      packageName = "isobject";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-2.1.0.tgz";
        sha1 = "f065561096a3f1da2ef46272f815c840d87e0c89";
      };
    };
    "randomatic-1.1.5" = {
      name = "randomatic";
      packageName = "randomatic";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/randomatic/-/randomatic-1.1.5.tgz";
        sha1 = "5e9ef5f2d573c67bd2b8124ae90b5156e457840b";
      };
    };
    "repeat-string-1.5.4" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.5.4.tgz";
        sha1 = "64ec0c91e0f4b475f90d5b643651e3e6e5b6c2d5";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "is-posix-bracket-0.1.1" = {
      name = "is-posix-bracket";
      packageName = "is-posix-bracket";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-posix-bracket/-/is-posix-bracket-0.1.1.tgz";
        sha1 = "3334dc79774368e92f016e6fbc0a88f5cd6e6bc4";
      };
    };
    "is-buffer-1.1.4" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.4.tgz";
        sha1 = "cfc86ccd5dc5a52fa80489111c6920c457e2d98b";
      };
    };
    "for-own-0.1.4" = {
      name = "for-own";
      packageName = "for-own";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-own/-/for-own-0.1.4.tgz";
        sha1 = "0149b41a39088c7515f51ebe1c1386d45f935072";
      };
    };
    "is-extendable-0.1.1" = {
      name = "is-extendable";
      packageName = "is-extendable";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extendable/-/is-extendable-0.1.1.tgz";
        sha1 = "62b110e289a471418e3ec36a617d472e301dfc89";
      };
    };
    "for-in-0.1.6" = {
      name = "for-in";
      packageName = "for-in";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-in/-/for-in-0.1.6.tgz";
        sha1 = "c9f96e89bfad18a545af5ec3ed352a1d9e5b4dc8";
      };
    };
    "glob-base-0.3.0" = {
      name = "glob-base";
      packageName = "glob-base";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-base/-/glob-base-0.3.0.tgz";
        sha1 = "dbb164f6221b1c0b1ccf82aea328b497df0ea3c4";
      };
    };
    "is-dotfile-1.0.2" = {
      name = "is-dotfile";
      packageName = "is-dotfile";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-dotfile/-/is-dotfile-1.0.2.tgz";
        sha1 = "2c132383f39199f8edc268ca01b9b007d205cc4d";
      };
    };
    "is-equal-shallow-0.1.3" = {
      name = "is-equal-shallow";
      packageName = "is-equal-shallow";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-equal-shallow/-/is-equal-shallow-0.1.3.tgz";
        sha1 = "2238098fc221de0bcfa5d9eac4c45d638aa1c534";
      };
    };
    "is-primitive-2.0.0" = {
      name = "is-primitive";
      packageName = "is-primitive";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-primitive/-/is-primitive-2.0.0.tgz";
        sha1 = "207bab91638499c07b2adf240a41a87210034575";
      };
    };
    "binary-extensions-1.7.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-1.7.0.tgz";
        sha1 = "6c1610db163abfb34edfe42fa423343a1e01185d";
      };
    };
    "graceful-fs-4.1.9" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.9.tgz";
        sha1 = "baacba37d19d11f9d146d3578bc99958c3787e29";
      };
    };
    "minimatch-3.0.3" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.3.tgz";
        sha1 = "2a4e4090b96b2db06a9d7df01055a62a77c9b774";
      };
    };
    "readable-stream-2.1.5" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.1.5.tgz";
        sha1 = "66fa8b720e1438b364681f2ad1a63c618448c9d0";
      };
    };
    "set-immediate-shim-1.0.1" = {
      name = "set-immediate-shim";
      packageName = "set-immediate-shim";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-immediate-shim/-/set-immediate-shim-1.0.1.tgz";
        sha1 = "4b2b1b27eb808a9f8dcc481a58e5e56f599f3f61";
      };
    };
    "brace-expansion-1.1.6" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.6.tgz";
        sha1 = "7197d7eaa9b87e648390ea61fc66c84427420df9";
      };
    };
    "balanced-match-0.4.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-0.4.2.tgz";
        sha1 = "cb3f3e3c732dc0f01ee70b403f302e61d7709838";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "buffer-shims-1.0.0" = {
      name = "buffer-shims";
      packageName = "buffer-shims";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-shims/-/buffer-shims-1.0.0.tgz";
        sha1 = "9978ce317388c649ad8793028c3477ef044a8b51";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "nan-2.4.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.4.0.tgz";
        sha1 = "fb3c59d45fe4effe215f0b890f8adf6eb32d2232";
      };
    };
    "node-pre-gyp-0.6.30" = {
      name = "node-pre-gyp";
      packageName = "node-pre-gyp";
      version = "0.6.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.30.tgz";
        sha1 = "64d3073a6f573003717ccfe30c89023297babba1";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "npmlog-4.0.0" = {
      name = "npmlog";
      packageName = "npmlog";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/npmlog/-/npmlog-4.0.0.tgz";
        sha1 = "e094503961c70c1774eb76692080e8d578a9f88f";
      };
    };
    "rc-1.1.6" = {
      name = "rc";
      packageName = "rc";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/rc/-/rc-1.1.6.tgz";
        sha1 = "43651b76b6ae53b5c802f1151fa3fc3b059969c9";
      };
    };
    "request-2.75.0" = {
      name = "request";
      packageName = "request";
      version = "2.75.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.75.0.tgz";
        sha1 = "d2b8268a286da13eaa5d01adf5d18cc90f657d93";
      };
    };
    "rimraf-2.5.4" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.5.4.tgz";
        sha1 = "96800093cbf1a0c86bd95b4625467535c29dfa04";
      };
    };
    "semver-5.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.3.0.tgz";
        sha1 = "9b2ce5d3de02d17c6012ad326aa6b4d0cf54f94f";
      };
    };
    "tar-2.2.1" = {
      name = "tar";
      packageName = "tar";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar/-/tar-2.2.1.tgz";
        sha1 = "8e4d2a256c0e2185c6b18ad694aec968b83cb1d1";
      };
    };
    "tar-pack-3.1.4" = {
      name = "tar-pack";
      packageName = "tar-pack";
      version = "3.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar-pack/-/tar-pack-3.1.4.tgz";
        sha1 = "bc8cf9a22f5832739f12f3910dac1eb97b49708c";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "abbrev-1.0.9" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.0.9.tgz";
        sha1 = "91b4792588a7738c25f35dd6f63752a2f8776135";
      };
    };
    "are-we-there-yet-1.1.2" = {
      name = "are-we-there-yet";
      packageName = "are-we-there-yet";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/are-we-there-yet/-/are-we-there-yet-1.1.2.tgz";
        sha1 = "80e470e95a084794fe1899262c5667c6e88de1b3";
      };
    };
    "console-control-strings-1.1.0" = {
      name = "console-control-strings";
      packageName = "console-control-strings";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-control-strings/-/console-control-strings-1.1.0.tgz";
        sha1 = "3d7cf4464db6446ea644bf4b39507f9851008e8e";
      };
    };
    "gauge-2.6.0" = {
      name = "gauge";
      packageName = "gauge";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gauge/-/gauge-2.6.0.tgz";
        sha1 = "d35301ad18e96902b4751dcbbe40f4218b942a46";
      };
    };
    "set-blocking-2.0.0" = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "045f9782d011ae9a6803ddd382b24392b3d890f7";
      };
    };
    "delegates-1.0.0" = {
      name = "delegates";
      packageName = "delegates";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delegates/-/delegates-1.0.0.tgz";
        sha1 = "84c6e159b81904fdca59a0ef44cd870d31250f9a";
      };
    };
    "aproba-1.0.4" = {
      name = "aproba";
      packageName = "aproba";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/aproba/-/aproba-1.0.4.tgz";
        sha1 = "2713680775e7614c8ba186c065d4e2e52d1072c0";
      };
    };
    "has-color-0.1.7" = {
      name = "has-color";
      packageName = "has-color";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-color/-/has-color-0.1.7.tgz";
        sha1 = "67144a5260c34fc3cca677d041daf52fe7b78b2f";
      };
    };
    "has-unicode-2.0.1" = {
      name = "has-unicode";
      packageName = "has-unicode";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-unicode/-/has-unicode-2.0.1.tgz";
        sha1 = "e0e6fe6a28cf51138855e086d1691e771de2a8b9";
      };
    };
    "object-assign-4.1.0" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.0.tgz";
        sha1 = "7a3b3d0e98063d43f4c03f2e8ae6cd51a86883a0";
      };
    };
    "signal-exit-3.0.1" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.1.tgz";
        sha1 = "5a4c884992b63a7acd9badb7894c3ee9cfccad81";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "wide-align-1.1.0" = {
      name = "wide-align";
      packageName = "wide-align";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wide-align/-/wide-align-1.1.0.tgz";
        sha1 = "40edde802a71fea1f070da3e62dcda2e7add96ad";
      };
    };
    "code-point-at-1.0.1" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.0.1.tgz";
        sha1 = "1104cd34f9b5b45d3eba88f1babc1924e1ce35fb";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "deep-extend-0.4.1" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.4.1.tgz";
        sha1 = "efe4113d08085f4e6f9687759810f807469e2253";
      };
    };
    "ini-1.3.4" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.4.tgz";
        sha1 = "0537cb79daf59b59a1a517dff706c86ec039162e";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "strip-json-comments-1.0.4" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.4.tgz";
        sha1 = "1e15fbcac97d3ee99bf2d73b4c656b082bbafb91";
      };
    };
    "aws-sign2-0.6.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz";
        sha1 = "14342dd38dbcc94d0e5b87d763cd63612c0e794f";
      };
    };
    "aws4-1.5.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.5.0.tgz";
        sha1 = "0a29ffb79c31c9e712eeb087e8e7a64b4a56d755";
      };
    };
    "bl-1.1.2" = {
      name = "bl";
      packageName = "bl";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-1.1.2.tgz";
        sha1 = "fdca871a99713aa00d19e3bbba41c44787a65398";
      };
    };
    "caseless-0.11.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.11.0.tgz";
        sha1 = "715b96ea9841593cc33067923f5ec60ebda4f7d7";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "extend-3.0.0" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.0.tgz";
        sha1 = "5a474353b9f3353ddd8176dfd37b91c83a46f1d4";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.0.0" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.0.0.tgz";
        sha1 = "6f0aebadcc5da16c13e1ecc11137d85f9b883b25";
      };
    };
    "har-validator-2.0.6" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-2.0.6.tgz";
        sha1 = "cdcbc08188265ad119b6a5a7c8ab70eecfb5d27d";
      };
    };
    "hawk-3.1.3" = {
      name = "hawk";
      packageName = "hawk";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz";
        sha1 = "078444bd7c1640b0fe540d2c9b73d59678e8e1c4";
      };
    };
    "http-signature-1.1.1" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.1.1.tgz";
        sha1 = "df72e267066cd0ac67fb76adf8e134a8fbcf91bf";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "mime-types-2.1.12" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.12.tgz";
        sha1 = "152ba256777020dd4663f54c2e7bc26381e71729";
      };
    };
    "node-uuid-1.4.7" = {
      name = "node-uuid";
      packageName = "node-uuid";
      version = "1.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz";
        sha1 = "6da5a17668c4b3dd59623bda11cf7fa4c1f60a6f";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "qs-6.2.1" = {
      name = "qs";
      packageName = "qs";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.2.1.tgz";
        sha1 = "ce03c5ff0935bc1d9d69a9f14cbd18e568d67625";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "tough-cookie-2.3.1" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.1.tgz";
        sha1 = "99c77dfbb7d804249e8a299d4cb0fd81fef083fd";
      };
    };
    "tunnel-agent-0.4.3" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.4.3.tgz";
        sha1 = "6373db76909fe570e08d73583365ed828a74eeeb";
      };
    };
    "readable-stream-2.0.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz";
        sha1 = "8f90341e68a53ccc928788dacfcd11b36eb9b78e";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "commander-2.9.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.9.0.tgz";
        sha1 = "9c99094176e12240cb22d6c5146098400fe0f7d4";
      };
    };
    "is-my-json-valid-2.15.0" = {
      name = "is-my-json-valid";
      packageName = "is-my-json-valid";
      version = "2.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-my-json-valid/-/is-my-json-valid-2.15.0.tgz";
        sha1 = "936edda3ca3c211fd98f3b2d3e08da43f7b2915b";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "graceful-readlink-1.0.1" = {
      name = "graceful-readlink";
      packageName = "graceful-readlink";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz";
        sha1 = "4cafad76bc62f02fa039b2f94e9a3dd3a391a725";
      };
    };
    "generate-function-2.0.0" = {
      name = "generate-function";
      packageName = "generate-function";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-function/-/generate-function-2.0.0.tgz";
        sha1 = "6858fe7c0969b7d4e9093337647ac79f60dfbe74";
      };
    };
    "generate-object-property-1.2.0" = {
      name = "generate-object-property";
      packageName = "generate-object-property";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-object-property/-/generate-object-property-1.2.0.tgz";
        sha1 = "9c0e1c40308ce804f4783618b937fa88f99d50d0";
      };
    };
    "jsonpointer-4.0.0" = {
      name = "jsonpointer";
      packageName = "jsonpointer";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonpointer/-/jsonpointer-4.0.0.tgz";
        sha1 = "6661e161d2fc445f19f98430231343722e1fcbd5";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "is-property-1.0.2" = {
      name = "is-property";
      packageName = "is-property";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-property/-/is-property-1.0.2.tgz";
        sha1 = "57fe1c4e48474edd65b09911f26b1cd4095dda84";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "hoek-2.16.3" = {
      name = "hoek";
      packageName = "hoek";
      version = "2.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz";
        sha1 = "20bb7403d3cea398e91dc4710a8ff1b8274a25ed";
      };
    };
    "boom-2.10.1" = {
      name = "boom";
      packageName = "boom";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz";
        sha1 = "39c8918ceff5799f83f9492a848f625add0c766f";
      };
    };
    "cryptiles-2.0.5" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-2.0.5.tgz";
        sha1 = "3bdfecdc608147c1c67202fa291e7dca59eaa3b8";
      };
    };
    "sntp-1.0.9" = {
      name = "sntp";
      packageName = "sntp";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-1.0.9.tgz";
        sha1 = "6541184cc90aeea6c6e7b35e2659082443c66198";
      };
    };
    "assert-plus-0.2.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.2.0.tgz";
        sha1 = "d74e1b87e7affc0db8aadb7021f3fe48101ab234";
      };
    };
    "jsprim-1.3.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.3.1.tgz";
        sha1 = "2a7256f70412a29ee3670aaca625994c4dcff252";
      };
    };
    "sshpk-1.10.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.10.1.tgz";
        sha1 = "30e1a5d329244974a1af61511339d595af6638b0";
      };
    };
    "extsprintf-1.0.2" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.0.2.tgz";
        sha1 = "e1080e0658e300b06294990cc70e1502235fd550";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "verror-1.3.6" = {
      name = "verror";
      packageName = "verror";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.3.6.tgz";
        sha1 = "cff5df12946d297d2baaefaa2689e25be01c005c";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "dashdash-1.14.0" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.0.tgz";
        sha1 = "29e486c5418bf0f356034a993d51686a33e84141";
      };
    };
    "getpass-0.1.6" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.6.tgz";
        sha1 = "283ffd9fc1256840875311c1b60e8c40187110e6";
      };
    };
    "jsbn-0.1.0" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.0.tgz";
        sha1 = "650987da0dd74f4ebf5a11377a2aa2d273e97dfd";
      };
    };
    "tweetnacl-0.14.3" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.3.tgz";
        sha1 = "3da382f670f25ded78d7b3d1792119bca0b7132d";
      };
    };
    "jodid25519-1.0.2" = {
      name = "jodid25519";
      packageName = "jodid25519";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jodid25519/-/jodid25519-1.0.2.tgz";
        sha1 = "06d4912255093419477d425633606e0e90782967";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "bcrypt-pbkdf-1.0.0" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.0.tgz";
        sha1 = "3ca76b85241c7170bf7d9703e7b9aa74630040d4";
      };
    };
    "mime-db-1.24.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.24.0.tgz";
        sha1 = "e2d13f939f0016c6e4e9ad25a8652f126c467f0c";
      };
    };
    "glob-7.1.1" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.1.tgz";
        sha1 = "805211df04faaf1c63a3600306cdf5ade50b2ec8";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "block-stream-0.0.9" = {
      name = "block-stream";
      packageName = "block-stream";
      version = "0.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/block-stream/-/block-stream-0.0.9.tgz";
        sha1 = "13ebfe778a03205cfe03751481ebb4b3300c126a";
      };
    };
    "fstream-1.0.10" = {
      name = "fstream";
      packageName = "fstream";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/fstream/-/fstream-1.0.10.tgz";
        sha1 = "604e8a92fe26ffd9f6fae30399d4984e1ab22822";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "fstream-ignore-1.0.5" = {
      name = "fstream-ignore";
      packageName = "fstream-ignore";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/fstream-ignore/-/fstream-ignore-1.0.5.tgz";
        sha1 = "9c31dae34767018fe1d249b24dada67d092da105";
      };
    };
    "once-1.3.3" = {
      name = "once";
      packageName = "once";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.3.3.tgz";
        sha1 = "b2e261557ce4c314ec8304f3fa82663e4297ca20";
      };
    };
    "uid-number-0.0.6" = {
      name = "uid-number";
      packageName = "uid-number";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/uid-number/-/uid-number-0.0.6.tgz";
        sha1 = "0ea10e8035e8eb5b8e4449f06da1c730663baa81";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "deep-is-0.1.3" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.3.tgz";
        sha1 = "b369d6fb5dbc13eecf524f91b070feedc357cf34";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "fast-levenshtein-2.0.5" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.5.tgz";
        sha1 = "bd33145744519ab1c36c3ee9f31f08e9079b67f2";
      };
    };
    "source-map-support-0.4.3" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.4.3.tgz";
        sha1 = "693c8383d4389a4569486987c219744dfc601685";
      };
    };
    "source-map-0.5.6" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.6.tgz";
        sha1 = "75ce38f52bf0733c5a7f0c118d81334a2bb5f412";
      };
    };
    "interpret-1.0.1" = {
      name = "interpret";
      packageName = "interpret";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/interpret/-/interpret-1.0.1.tgz";
        sha1 = "d579fb7f693b858004947af39fa0db49f795602c";
      };
    };
    "rechoir-0.6.2" = {
      name = "rechoir";
      packageName = "rechoir";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rechoir/-/rechoir-0.6.2.tgz";
        sha1 = "85204b54dba82d5742e28c96756ef43af50e3384";
      };
    };
    "resolve-1.1.7" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.1.7.tgz";
        sha1 = "203114d82ad2c5ed9e8e0411b3932875e889e97b";
      };
    };
  };
in
{
  riot-cli = nodeEnv.buildNodePackage {
    name = "riot-cli";
    packageName = "riot-cli";
    version = "2.6.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/riot-cli/-/riot-cli-2.6.2.tgz";
      sha1 = "2efd43bed8b286d558dc09b55a5f0e80c9f10c09";
    };
    dependencies = [
      (sources."chalk-1.1.3" // {
        dependencies = [
          sources."ansi-styles-2.2.1"
          sources."escape-string-regexp-1.0.5"
          (sources."has-ansi-2.0.0" // {
            dependencies = [
              sources."ansi-regex-2.0.0"
            ];
          })
          (sources."strip-ansi-3.0.1" // {
            dependencies = [
              sources."ansi-regex-2.0.0"
            ];
          })
          sources."supports-color-2.0.0"
        ];
      })
      (sources."chokidar-1.6.0" // {
        dependencies = [
          (sources."anymatch-1.3.0" // {
            dependencies = [
              sources."arrify-1.0.1"
              (sources."micromatch-2.3.11" // {
                dependencies = [
                  (sources."arr-diff-2.0.0" // {
                    dependencies = [
                      sources."arr-flatten-1.0.1"
                    ];
                  })
                  sources."array-unique-0.2.1"
                  (sources."braces-1.8.5" // {
                    dependencies = [
                      (sources."expand-range-1.8.2" // {
                        dependencies = [
                          (sources."fill-range-2.2.3" // {
                            dependencies = [
                              sources."is-number-2.1.0"
                              (sources."isobject-2.1.0" // {
                                dependencies = [
                                  sources."isarray-1.0.0"
                                ];
                              })
                              sources."randomatic-1.1.5"
                              sources."repeat-string-1.5.4"
                            ];
                          })
                        ];
                      })
                      sources."preserve-0.2.0"
                      sources."repeat-element-1.1.2"
                    ];
                  })
                  (sources."expand-brackets-0.1.5" // {
                    dependencies = [
                      sources."is-posix-bracket-0.1.1"
                    ];
                  })
                  sources."extglob-0.3.2"
                  sources."filename-regex-2.0.0"
                  sources."is-extglob-1.0.0"
                  (sources."kind-of-3.0.4" // {
                    dependencies = [
                      sources."is-buffer-1.1.4"
                    ];
                  })
                  sources."normalize-path-2.0.1"
                  (sources."object.omit-2.0.0" // {
                    dependencies = [
                      (sources."for-own-0.1.4" // {
                        dependencies = [
                          sources."for-in-0.1.6"
                        ];
                      })
                      sources."is-extendable-0.1.1"
                    ];
                  })
                  (sources."parse-glob-3.0.4" // {
                    dependencies = [
                      sources."glob-base-0.3.0"
                      sources."is-dotfile-1.0.2"
                    ];
                  })
                  (sources."regex-cache-0.4.3" // {
                    dependencies = [
                      sources."is-equal-shallow-0.1.3"
                      sources."is-primitive-2.0.0"
                    ];
                  })
                ];
              })
            ];
          })
          sources."async-each-1.0.1"
          sources."glob-parent-2.0.0"
          sources."inherits-2.0.3"
          (sources."is-binary-path-1.0.1" // {
            dependencies = [
              sources."binary-extensions-1.7.0"
            ];
          })
          (sources."is-glob-2.0.1" // {
            dependencies = [
              sources."is-extglob-1.0.0"
            ];
          })
          sources."path-is-absolute-1.0.1"
          (sources."readdirp-2.1.0" // {
            dependencies = [
              sources."graceful-fs-4.1.9"
              (sources."minimatch-3.0.3" // {
                dependencies = [
                  (sources."brace-expansion-1.1.6" // {
                    dependencies = [
                      sources."balanced-match-0.4.2"
                      sources."concat-map-0.0.1"
                    ];
                  })
                ];
              })
              (sources."readable-stream-2.1.5" // {
                dependencies = [
                  sources."buffer-shims-1.0.0"
                  sources."core-util-is-1.0.2"
                  sources."isarray-1.0.0"
                  sources."process-nextick-args-1.0.7"
                  sources."string_decoder-0.10.31"
                  sources."util-deprecate-1.0.2"
                ];
              })
              sources."set-immediate-shim-1.0.1"
            ];
          })
          (sources."fsevents-1.0.14" // {
            dependencies = [
              sources."nan-2.4.0"
              (sources."node-pre-gyp-0.6.30" // {
                dependencies = [
                  (sources."mkdirp-0.5.1" // {
                    dependencies = [
                      sources."minimist-0.0.8"
                    ];
                  })
                  (sources."nopt-3.0.6" // {
                    dependencies = [
                      sources."abbrev-1.0.9"
                    ];
                  })
                  (sources."npmlog-4.0.0" // {
                    dependencies = [
                      (sources."are-we-there-yet-1.1.2" // {
                        dependencies = [
                          sources."delegates-1.0.0"
                          (sources."readable-stream-2.1.5" // {
                            dependencies = [
                              sources."buffer-shims-1.0.0"
                              sources."core-util-is-1.0.2"
                              sources."isarray-1.0.0"
                              sources."process-nextick-args-1.0.7"
                              sources."string_decoder-0.10.31"
                              sources."util-deprecate-1.0.2"
                            ];
                          })
                        ];
                      })
                      sources."console-control-strings-1.1.0"
                      (sources."gauge-2.6.0" // {
                        dependencies = [
                          sources."aproba-1.0.4"
                          sources."has-color-0.1.7"
                          sources."has-unicode-2.0.1"
                          sources."object-assign-4.1.0"
                          sources."signal-exit-3.0.1"
                          (sources."string-width-1.0.2" // {
                            dependencies = [
                              (sources."code-point-at-1.0.1" // {
                                dependencies = [
                                  sources."number-is-nan-1.0.1"
                                ];
                              })
                              (sources."is-fullwidth-code-point-1.0.0" // {
                                dependencies = [
                                  sources."number-is-nan-1.0.1"
                                ];
                              })
                            ];
                          })
                          (sources."strip-ansi-3.0.1" // {
                            dependencies = [
                              sources."ansi-regex-2.0.0"
                            ];
                          })
                          sources."wide-align-1.1.0"
                        ];
                      })
                      sources."set-blocking-2.0.0"
                    ];
                  })
                  (sources."rc-1.1.6" // {
                    dependencies = [
                      sources."deep-extend-0.4.1"
                      sources."ini-1.3.4"
                      sources."minimist-1.2.0"
                      sources."strip-json-comments-1.0.4"
                    ];
                  })
                  (sources."request-2.75.0" // {
                    dependencies = [
                      sources."aws-sign2-0.6.0"
                      sources."aws4-1.5.0"
                      (sources."bl-1.1.2" // {
                        dependencies = [
                          (sources."readable-stream-2.0.6" // {
                            dependencies = [
                              sources."core-util-is-1.0.2"
                              sources."isarray-1.0.0"
                              sources."process-nextick-args-1.0.7"
                              sources."string_decoder-0.10.31"
                              sources."util-deprecate-1.0.2"
                            ];
                          })
                        ];
                      })
                      sources."caseless-0.11.0"
                      (sources."combined-stream-1.0.5" // {
                        dependencies = [
                          sources."delayed-stream-1.0.0"
                        ];
                      })
                      sources."extend-3.0.0"
                      sources."forever-agent-0.6.1"
                      (sources."form-data-2.0.0" // {
                        dependencies = [
                          sources."asynckit-0.4.0"
                        ];
                      })
                      (sources."har-validator-2.0.6" // {
                        dependencies = [
                          (sources."commander-2.9.0" // {
                            dependencies = [
                              sources."graceful-readlink-1.0.1"
                            ];
                          })
                          (sources."is-my-json-valid-2.15.0" // {
                            dependencies = [
                              sources."generate-function-2.0.0"
                              (sources."generate-object-property-1.2.0" // {
                                dependencies = [
                                  sources."is-property-1.0.2"
                                ];
                              })
                              sources."jsonpointer-4.0.0"
                              sources."xtend-4.0.1"
                            ];
                          })
                          (sources."pinkie-promise-2.0.1" // {
                            dependencies = [
                              sources."pinkie-2.0.4"
                            ];
                          })
                        ];
                      })
                      (sources."hawk-3.1.3" // {
                        dependencies = [
                          sources."hoek-2.16.3"
                          sources."boom-2.10.1"
                          sources."cryptiles-2.0.5"
                          sources."sntp-1.0.9"
                        ];
                      })
                      (sources."http-signature-1.1.1" // {
                        dependencies = [
                          sources."assert-plus-0.2.0"
                          (sources."jsprim-1.3.1" // {
                            dependencies = [
                              sources."extsprintf-1.0.2"
                              sources."json-schema-0.2.3"
                              sources."verror-1.3.6"
                            ];
                          })
                          (sources."sshpk-1.10.1" // {
                            dependencies = [
                              sources."asn1-0.2.3"
                              sources."assert-plus-1.0.0"
                              sources."dashdash-1.14.0"
                              sources."getpass-0.1.6"
                              sources."jsbn-0.1.0"
                              sources."tweetnacl-0.14.3"
                              sources."jodid25519-1.0.2"
                              sources."ecc-jsbn-0.1.1"
                              sources."bcrypt-pbkdf-1.0.0"
                            ];
                          })
                        ];
                      })
                      sources."is-typedarray-1.0.0"
                      sources."isstream-0.1.2"
                      sources."json-stringify-safe-5.0.1"
                      (sources."mime-types-2.1.12" // {
                        dependencies = [
                          sources."mime-db-1.24.0"
                        ];
                      })
                      sources."node-uuid-1.4.7"
                      sources."oauth-sign-0.8.2"
                      sources."qs-6.2.1"
                      sources."stringstream-0.0.5"
                      sources."tough-cookie-2.3.1"
                      sources."tunnel-agent-0.4.3"
                    ];
                  })
                  (sources."rimraf-2.5.4" // {
                    dependencies = [
                      (sources."glob-7.1.1" // {
                        dependencies = [
                          sources."fs.realpath-1.0.0"
                          (sources."inflight-1.0.6" // {
                            dependencies = [
                              sources."wrappy-1.0.2"
                            ];
                          })
                          (sources."minimatch-3.0.3" // {
                            dependencies = [
                              (sources."brace-expansion-1.1.6" // {
                                dependencies = [
                                  sources."balanced-match-0.4.2"
                                  sources."concat-map-0.0.1"
                                ];
                              })
                            ];
                          })
                          (sources."once-1.4.0" // {
                            dependencies = [
                              sources."wrappy-1.0.2"
                            ];
                          })
                        ];
                      })
                    ];
                  })
                  sources."semver-5.3.0"
                  (sources."tar-2.2.1" // {
                    dependencies = [
                      sources."block-stream-0.0.9"
                      (sources."fstream-1.0.10" // {
                        dependencies = [
                          sources."graceful-fs-4.1.9"
                        ];
                      })
                    ];
                  })
                  (sources."tar-pack-3.1.4" // {
                    dependencies = [
                      (sources."debug-2.2.0" // {
                        dependencies = [
                          sources."ms-0.7.1"
                        ];
                      })
                      (sources."fstream-1.0.10" // {
                        dependencies = [
                          sources."graceful-fs-4.1.9"
                        ];
                      })
                      (sources."fstream-ignore-1.0.5" // {
                        dependencies = [
                          (sources."minimatch-3.0.3" // {
                            dependencies = [
                              (sources."brace-expansion-1.1.6" // {
                                dependencies = [
                                  sources."balanced-match-0.4.2"
                                  sources."concat-map-0.0.1"
                                ];
                              })
                            ];
                          })
                        ];
                      })
                      (sources."once-1.3.3" // {
                        dependencies = [
                          sources."wrappy-1.0.2"
                        ];
                      })
                      (sources."readable-stream-2.1.5" // {
                        dependencies = [
                          sources."buffer-shims-1.0.0"
                          sources."core-util-is-1.0.2"
                          sources."isarray-1.0.0"
                          sources."process-nextick-args-1.0.7"
                          sources."string_decoder-0.10.31"
                          sources."util-deprecate-1.0.2"
                        ];
                      })
                      sources."uid-number-0.0.6"
                    ];
                  })
                ];
              })
            ];
          })
        ];
      })
      sources."co-4.6.0"
      (sources."optionator-0.8.2" // {
        dependencies = [
          sources."prelude-ls-1.1.2"
          sources."deep-is-0.1.3"
          sources."wordwrap-1.0.0"
          sources."type-check-0.3.2"
          sources."levn-0.3.0"
          sources."fast-levenshtein-2.0.5"
        ];
      })
      sources."riot-compiler-2.5.5"
      (sources."rollup-0.36.3" // {
        dependencies = [
          (sources."source-map-support-0.4.3" // {
            dependencies = [
              sources."source-map-0.5.6"
            ];
          })
        ];
      })
      (sources."shelljs-0.7.4" // {
        dependencies = [
          (sources."glob-7.1.1" // {
            dependencies = [
              sources."fs.realpath-1.0.0"
              (sources."inflight-1.0.6" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              sources."inherits-2.0.3"
              (sources."minimatch-3.0.3" // {
                dependencies = [
                  (sources."brace-expansion-1.1.6" // {
                    dependencies = [
                      sources."balanced-match-0.4.2"
                      sources."concat-map-0.0.1"
                    ];
                  })
                ];
              })
              (sources."once-1.4.0" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              sources."path-is-absolute-1.0.1"
            ];
          })
          sources."interpret-1.0.1"
          (sources."rechoir-0.6.2" // {
            dependencies = [
              sources."resolve-1.1.7"
            ];
          })
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Riot command line utility";
      homepage = "https://github.com/riot/cli#readme";
      license = "MIT";
    };
    production = true;
  };
}